### ISSUE TITLE
PIA uses new cert and port

### ISSUE THREAD

**Issue by currowth** [mr-canoehead/vpn_client_gateway#19]
the new openvpn.zip includes new certs "ca.rsa.2048.crt" and "crl.rsa.2048.pem". The config files also uses new port. Please change 

remote us-west.privateinternetaccess.com 1194 
to
remote us-west.privateinternetaccess.com 1198

I also had to add
cipher aes-128-cbc

My final server.conf looks like this
client
dev tun0
proto udp
remote ca.privateinternetaccess.com 1198
resolv-retry infinite
keepalive 10 60
nobind
persist-key
redirect-gateway
cipher aes-128-cbc
ca ca.rsa.2048.crt
tls-client
remote-cert-tls server
auth-user-pass auth.txt
comp-lzo
verb 1
reneg-sec 0
crl-verify crl.rsa.2048.pem

**Comment by mr-canoehead** [comment]
Thanks for submitting this, I have updated the wiki and the PIA server.conf to include these changes. Interesting to note that while PIA provides aes-128 certs their server cipher is set to blowfish:
`WARNING: 'cipher' is used inconsistently, local='cipher AES-128-CBC', remote='cipher BF-CBC'`
Including the aes-128-cbc cipher in the config file overrides the server setting:
`Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key`
