### ISSUE TITLE
web folder paths for Pi-hole compatibility

### ISSUE THREAD

**Issue by noosso** [mr-canoehead/vpn_client_gateway#26]
Install vpnmgmt in subfolder /var/www/html/vpnmgmt
after changing vpn Pi-hole says Website Blocked
since vpnmgmt wants to go back to the root folder.

Since the structure was not changed, just one level deeper, vpnmgmt should pull it's path dynamic.
Not return home but then one level deeper.

Path to index.php is /var/www/html/vpnmgmt/index.php.

**Comment by mr-canoehead** [comment]
I have modified the URL handling code in index.php to support arbitrary paths. The code now gets the current URL and strips off parameters, rather than just using the root path.

Thanks for submitting this issue.
