### ISSUE TITLE
How connecting new device looks like?

### ISSUE THREAD

**Issue by patjakubik** [mr-canoehead/vpn_client_gateway#44]
I'm looking into getting started with this project. Does every client device need to be configured somehow before connecting or they will automatically connect via VPN automatically? Could someone elaborate?

**Comment by Hobbabobba** [comment]
first you need to know the IP-address of your vpn-gateway (pi) inside of your LAN. if it is 192.168.8.19 (example) you will enter this address 192.168.8.19 as gateway and dns-server in the IPv4-settings of the client.

**Comment by mr-canoehead** [comment]
Closing this issue, the question was answered by Hobbabobba.
It would be helpful to create a basic network diagram to give new users an understanding of how the VPN Client Gateway will integrate into their network, I'll add this to my 'to-do' list.

**Comment by mr-canoehead** [comment]
I have created a network diagram for a basic installation of the VPN Client Gateway, you can view it via the following link:

https://gist.github.com/mr-canoehead/09d1dde3fd724f822edcb19cd95a6ed5

I would greatly appreciate any feedback you may have on it!

Thanks,
Chris
