### ISSUE TITLE
[SUGGESTION] Alternative to "sudo pip install lxml"

### ISSUE THREAD

**Issue by melwyn001** [mr-canoehead/vpn_client_gateway#54]
The "sudo pip install lxml" command at [here](https://github.com/mr-canoehead/vpn_client_gateway/wiki/Installation-Guide-Part-3:-Install-web-server,-application-server,-and-web-page-files#install-the-application-server) didn't complete building for 2+ hrs on my Pi. So, while looking for an alternative solution, I found one [here](https://stackoverflow.com/a/57853801/11427313), which is pre-built package. Did the job for me. Might be worth looking into. Cheers.

**Comment by mr-canoehead** [comment]
Wow, this is great! I rebuilt my VPN Client Gateway test setup using the python-lxml package instead of lxml, it installed quickly and all the application functions are working as expected. I have updated the install guide with the revised installation step.

Thank you for submitting this issue!
