### ISSUE TITLE
Have to "sudo service nginx restart" on every reset

### ISSUE THREAD

**Issue by izo1** [mr-canoehead/vpn_client_gateway#60]
Hi there this is the third time I am trying to install the server, everything works so far and it connects on reboot (soft or hard) but the web server needs to be restarted for the web portal to work.

Is this normal?

**Comment by mr-canoehead** [comment]
No this is not normal behavior; the services (nginx, vpncgw, openvpn) should all start automatically on reboot/cold boot. I reinstalled the project on my test RPi this morning using the latest Raspberry Pi OS Lite (2020-08-20), and am not seeing this issue. All services start normally after a reboot/cold boot. I have not received any other reports of this issue.

What is displayed when you try to access the management web page via a browser? Does it just fail to connect?

Are you running Raspberry Pi OS Lite?

After a reboot / cold boot, what is the status of the nginx service? Run the following command:

`sudo systemctl status nginx`

The output on my system is as follows:
```
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-09-10 12:40:49 PDT; 1h 32min ago
     Docs: man:nginx(8)
  Process: 629 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 630 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 631 (nginx)
    Tasks: 5 (limit: 2184)
   CGroup: /system.slice/nginx.service
           ├─631 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─632 nginx: worker process
           ├─633 nginx: worker process
           ├─634 nginx: worker process
           └─635 nginx: worker process
```

Do you see any nginx related errors in `/var/log/syslog`?

Thanks,
Chris

**Comment by izo1** [comment]
Hi thanks for the response.

Running Raspberry Pi 3B+ with latest Raspian OS (full version).

Basically the nginx web ui does load but it gets stuck on "Gateway..." and the spinning wheel and doesn't show anything...When I run the restart command (after a fresh boot) everything populates properly like the VPN servers and "active" area. The service does load fine after rebooting though and the killswitch works too. This is the 3rd time I'm trying a fresh install, not an expert but definitely followed the guide to a T.

Here's my output (after fresh reboot):

> nginx.service - A high performance web server and a reverse proxy server
>    Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: en
>    Active: active (running) since Thu 2020-09-10 16:11:18 PDT; 4min 36s ago
>      Docs: man:nginx(8)
>   Process: 540 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process o
>   Process: 541 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=
>  Main PID: 542 (nginx)
>     Tasks: 5 (limit: 2184)
>    CGroup: /system.slice/nginx.service
>            ├─542 nginx: master process /usr/sbin/nginx -g daemon on; master_proc
>            ├─543 nginx: worker process
>            ├─544 nginx: worker process
>            ├─545 nginx: worker process
>            └─546 nginx: worker process



Some error snippets I found in /var/log/syslog/nginx

> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET / HTTP/1.1" 200 2617 "-" "M$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /styles/index.css HTTP/1.1"$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /scripts/socket.io.min.js H$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /scripts/main.js HTTP/1.1" $
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /images/openvpn_logo_powere$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /styles/index.css?v=0.06694$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /images/status_icons/loadin$
> 192.168.1.193 - - [08/Sep/2020:17:58:56 -0700] "GET /images/status_icons/loadin$
> 192.168.1.193 - - [08/Sep/2020:17:58:57 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:58:59 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:04 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:09 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:14 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:19 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:24 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:29 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:34 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:39 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:44 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:49 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:54 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:17:59:59 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:04 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:09 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:14 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:19 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:24 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:29 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:34 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:39 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:44 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:49 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:54 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:00:59 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:04 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:09 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:14 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:19 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:24 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:29 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:34 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:39 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:44 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:49 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:54 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:01:59 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:02:04 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET / HTTP/1.1" 304 0 "-" "Mozi$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /styles/index.css HTTP/1.1"$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /scripts/socket.io.min.js H$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /scripts/main.js HTTP/1.1" $
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /images/openvpn_logo_powere$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /styles/index.css?v=0.38678$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /images/status_icons/loadin$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /images/status_icons/loadin$
> 192.168.1.193 - - [08/Sep/2020:18:02:07 -0700] "GET /images/favicon.ico HTTP/1.$
> 192.168.1.193 - - [08/Sep/2020:18:02:08 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:02:10 -0700] "GET /styles/index.css?v=0.96496$
> 192.168.1.193 - - [08/Sep/2020:18:02:10 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "POST /socket.io/?EIO=3&transpor$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "POST /socket.io/?EIO=3&transpor$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/CA.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/US.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/GB.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/AU.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/SE.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/NL.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/FR.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/DE.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:11 -0700] "GET /images/flags/CH.svg HTTP/1$
> 192.168.1.193 - - [08/Sep/2020:18:02:18 -0700] "GET /images/status_icons/ok20.p$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /styles/index.css?v=0.236582$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "POST /socket.io/?EIO=3&transport$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "POST /socket.io/?EIO=3&transport$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/CA.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/US.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/AU.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/SE.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/GB.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/FR.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/NL.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/DE.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:45 -0700] "GET /images/flags/CH.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:46 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET / HTTP/1.1" 304 0 "-" "Mozil$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /styles/index.css HTTP/1.1" $
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /scripts/socket.io.min.js HT$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /scripts/main.js HTTP/1.1" 3$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/openvpn_logo_powered$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /styles/index.css?v=0.592164$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/status_icons/loading$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/status_icons/loading$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/favicon.ico HTTP/1.1$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "POST /socket.io/?EIO=3&transport$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /socket.io/?EIO=3&transport=$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "POST /socket.io/?EIO=3&transport$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/US.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/CA.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/GB.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/AU.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/SE.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/NL.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/FR.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/DE.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:47 -0700] "GET /images/flags/CH.svg HTTP/1.$
> 192.168.1.20 - - [08/Sep/2020:18:04:51 -0700] "GET /images/status_icons/ok20.pn$
> 192.168.1.193 - - [08/Sep/2020:18:04:51 -0700] "GET /socket.io/?EIO=3&transport$
> 192.168.1.194 - - [08/Sep/2020:18:05:51 -0700] "GET / HTTP/1.1" 304 0 "-" "Mozi$
> 192.168.1.194 - - [08/Sep/2020:18:05:51 -0700] "GET /styles/index.css HTTP/1.1"$
> 192.168.1.194 - - [08/Sep/2020:18:05:51 -0700] "GET /scripts/socket.io.min.js H$
> 192.168.1.194 - - [08/Sep/2020:18:05:51 -0700] "GET /scripts/main.js HTTP/1.1" $

and

> 2020/09/08 17:58:56 [error] 3087#3087: *2 connect() failed (111: Connection ref$
> 2020/09/08 17:58:56 [error] 3087#3087: *2 connect() failed (111: Connection ref$
> 2020/09/08 17:58:57 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:58:57 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:58:59 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:04 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:09 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:09 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:14 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:19 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:24 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:24 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:29 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:34 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:39 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:39 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:44 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:49 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 17:59:54 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:54 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 17:59:59 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:04 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:09 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:09 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:14 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:19 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:24 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:24 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:29 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:34 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:39 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:39 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:44 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:49 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:00:54 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:54 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:00:59 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:04 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:09 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:09 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:14 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:19 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:24 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:24 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:29 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:34 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:39 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:39 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:44 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:49 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:01:54 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:54 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:01:59 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:02:04 [error] 3089#3089: *3 no live upstreams while connecting to$
> 2020/09/08 18:02:07 [error] 3089#3089: *3 connect() failed (111: Connection ref$
> 2020/09/08 18:02:10 [error] 3087#3087: *32 connect() failed (111: Connection re$
> 2020/09/08 18:02:11 [error] 3088#3088: *37 connect() failed (111: Connection re$
> 2020/09/08 18:04:45 [error] 3087#3087: *48 connect() failed (111: Connection re$
> 2020/09/08 18:04:45 [error] 3089#3089: *54 connect() failed (111: Connection re$
> 2020/09/08 18:04:45 [error] 3088#3088: *49 connect() failed (111: Connection re$
> 2020/09/08 18:05:51 [error] 3087#3087: *77 connect() failed (111: Connection re$
> 2020/09/08 18:08:45 [alert] 3087#3087: *77 open socket #19 left in connection 9
> 2020/09/08 18:08:45 [alert] 3087#3087: *79 open socket #20 left in connection 10
> 2020/09/08 18:08:45 [alert] 3087#3087: aborting
> 2020/09/08 18:09:25 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:26 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:28 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:31 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:36 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:41 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:44 [error] 544#544: *3 connect() failed (111: Connection refus$
> 2020/09/08 18:09:46 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:09:48 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:09:50 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:06 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:11 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:16 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:21 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:26 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:31 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:36 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:41 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:46 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:51 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:10:56 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:01 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:06 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:11 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:16 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:21 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:26 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:31 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:36 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:41 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:46 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:51 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:11:56 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:01 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:06 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:11 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:16 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:21 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:26 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:31 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:36 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:41 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:46 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:51 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:12:56 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:01 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:06 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:11 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:16 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:21 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:26 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:31 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:36 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:41 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:46 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:51 [error] 546#546: *2 connect() failed (111: Connection refus$
> 2020/09/08 18:13:56 [error] 546#546: *2 connect() failed (111: Connection refus$

Also here's a realtime log after a fresh reboot and trying to access the webserver...and then when the web server hangs (although UI shows as described) I run `sudo service nginx restart` and this is what shows up in the log.

```
sudo tail -f /var/log/syslog
Sep 10 16:28:53 vpn systemd[2097]: Reached target Paths.
Sep 10 16:28:53 vpn systemd[2097]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Sep 10 16:28:53 vpn systemd[2097]: Listening on D-Bus User Message Bus Socket.
Sep 10 16:28:53 vpn systemd[2097]: Reached target Sockets.
Sep 10 16:28:53 vpn systemd[2097]: Reached target Basic System.
Sep 10 16:28:53 vpn systemd[2097]: Reached target Default.
Sep 10 16:28:53 vpn systemd[2097]: Startup finished in 168ms.
Sep 10 16:28:53 vpn systemd[1]: Started User Manager for UID 1000.
Sep 10 16:28:53 vpn systemd[1]: Started Session c2 of user pi.
Sep 10 16:28:56 vpn systemd[1]: Started Session c3 of user pi.
Sep 10 16:30:17 vpn systemd[1]: Stopping A high performance web server and a reverse proxy server...
Sep 10 16:30:17 vpn systemd[1]: nginx.service: Succeeded.
Sep 10 16:30:17 vpn systemd[1]: Stopped A high performance web server and a reverse proxy server.
Sep 10 16:30:17 vpn systemd[1]: Starting A high performance web server and a reverse proxy server...
Sep 10 16:30:17 vpn systemd[1]: Started A high performance web server and a reverse proxy server.
```

**Comment by mr-canoehead** [comment]
I was able to reproduce this issue by installing the 'full' version of Raspberry Pi OS ("Raspberry Pi OS 32-bit with desktop and recommended software"). It is caused by the fact that in this version of Raspberry Pi OS the hostname 'localhost' initially resolves to the IPv6 address ::1 instead of the IPv4 address 127.0.0.1. Not sure why the resolved address switches to IPv4 after restarting nginx.

There are a number of different ways to resolve the issue, including:
1) installing the project using Raspberry Pi OS Lite (as specified in the Wiki)
2) disabling the IPv6 stack via /etc/sysctl.conf
3) changing the proxy address in /etc/nginx/sites-available/vpncgw.conf from 'localhost' to '127.0.0.1'
4) changing the bind directive in the gunicorn service config file from '0.0.0.0:8000' to '[::]:8000' (this causes gunicorn to listen on both the IPv6 and IPv4 local address)

Option 3 is probably the most straightforward. To apply this change, do the following:
edit the nginx site configuration file:

`sudo nano /etc/nginx/sites-available/vpncgw.conf`

change the `proxy_pass` setting to:

`proxy_pass              http://127.0.0.1:8000/socket.io/;`

After making this change, reboot the system and try accessing the management web page.

**Comment by izo1** [comment]
Woow @mr-canoehead you're the best!
I will reinstall the whole thing with RPi OS Lite again in a little while, since it's working so perfectly right now.

Is this a bug with the Full version of RPi? Maybe I can report it to their team too.

Before I had issues with getting TorGuard to work so I had to sign up with PIA. Spent a day banging my head against the wall haha.

Thanks much!

**Comment by mr-canoehead** [comment]
I wouldn't call this a bug, I'd chalk it up to some sort of configuration difference between the two versions of Raspberry Pi OS. I always use the Lite version for my network appliance projects because it has a minimal amount of software included and it tends to have the fewest changes between releases.

It's possible to get this project working with TorGuard since they support OpenVPN, it would require development of a configuration file and server list XML file specific to TorGuard. PIA is the easier option since it is already supported by the project.

Chris
