### ISSUE TITLE
migration of newshosting VPN to privado / new config-files

### ISSUE THREAD

**Issue by Hobbabobba** [mr-canoehead/vpn_client_gateway#63]
newshosting moved their vpn service to privado vpn. Maybe someone already figured out a workaround or fix for the config files?

**Comment by Hobbabobba** [comment]
tried my first pull request ever to help the project :)

**Comment by mr-canoehead** [comment]
I have added a script to extract inline files from .ovpn configuration files:
vpn_client_gateway/application/scripts/extract_ifile.sh
use the --help option to see usage info

-Chris
