### ISSUE TITLE
Requesting data... issue

### ISSUE THREAD

**Issue by fateles** [mr-canoehead/vpn_client_gateway#66]
Hello,
I'm installing a new version from scratch on a new SD Card to replace my older version. I tried 2 times, one with PiHole and other without it, but I always have the requesting data on the web interface.
I entered all the installation lines as per the step-by-step. On both I have this error on _syslog_:

`piavpn env[5415]: The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)`

I tried older versions manually and just crashed even more with _"not implemented"_ errors.
Tried to install some modules but in the end just ended being worse with more erros. After the install I don't have any erros I can understand related to vpncgw. 

Dec 27 23:56:33 piavpn env[6007]: Traceback (most recent call last):
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Dec 27 23:56:33 piavpn env[6007]:     worker.init_process()
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/workers/geventlet.py", line 102, in init_process
Dec 27 23:56:33 piavpn env[6007]:     super(EventletWorker, self).init_process()
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 129, in init_process
Dec 27 23:56:33 piavpn env[6007]:     self.load_wsgi()
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
Dec 27 23:56:33 piavpn env[6007]:     self.wsgi = self.app.wsgi()
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
Dec 27 23:56:33 piavpn env[6007]:     self.callable = self.load()
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
Dec 27 23:56:33 piavpn env[6007]:     return self.load_wsgiapp()
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
Dec 27 23:56:33 piavpn env[6007]:     return util.import_app(self.app_uri)
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 375, in import_app
Dec 27 23:56:33 piavpn env[6007]:     __import__(module)
Dec 27 23:56:33 piavpn env[6007]:   File "/opt/vpncgw/vpncgw.py", line 20, in <module>
Dec 27 23:56:33 piavpn env[6007]:     from flask_socketio import SocketIO, emit
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 26, in <module>
Dec 27 23:56:33 piavpn env[6007]:     from .namespace import Namespace
Dec 27 23:56:33 piavpn env[6007]:   File "/usr/local/lib/python3.7/dist-packages/flask_socketio/namespace.py", line 1, in <module>
Dec 27 23:56:33 piavpn env[6007]:     from socketio import Namespace as _Namespace
Dec 27 23:56:33 piavpn env[6007]: ImportError: cannot import name 'Namespace' from 'socketio' (/usr/local/lib/python3.7/dist-packages/socketio/__init__.py)

Thank you for the help and all the work!

**Comment by mr-canoehead** [comment]
I re-installed my test system today and was able to replicate this issue. To resolve it I downloaded the latest socket.io client script and patched the system. After a reboot the management web page loaded properly.

To patch your existing installation:
```
wget https://cdn.socket.io/socket.io-3.0.1.min.js
sudo cp socket.io-3.0.1.min.js /var/www/html/scripts/socket.io.min.js
sudo reboot
```
I have now updated the socket.io client script included with the project files.

Thanks,
Chris

**Comment by fateles** [comment]
Hi Chris,

Thank you for your quick answer! Tried again, with a clean SD card, and PiHole + VPN Gateway is working perfectly! Great work! Have a great week!

**Comment by fateles** [comment]
Just to add something regarding the documentation:
The change server list the vpnservers.xml location is wrong. It should be /opt/vpncgw for this newer version.

Thank you again for everything.
