### ISSUE TITLE
TORGUARD??

### ISSUE THREAD

**Issue by RobotsAreCrazy** [mr-canoehead/vpn_client_gateway#69]
Hi, Can you see if you can add torguard vpn with wireguard support please??

**Comment by mr-canoehead** [comment]
WireGuard support is definitely something I'm considering adding in the future; more and more VPN providers are supporting it (some only via their proprietary client apps, others via the open source WireGuard client). This will require some significant work on the server app that I'm not in a position to undertake at the moment.

Meanwhile, supporting TorGuard should be straightforward using the standard OpenVPN client; it's just a matter of creating a vpnservers.xml file containing the list of TorGuard servers, and an OpenVPN configuration file (vpncgw.conf) that is compatible with their service. I am unable to create and test these configuration files as I don't have access to a TorGuard VPN account.

Thanks,
Chris
